[phases.setup]
nixPkgs = ["nodejs_22", "jdk17"]

[phases.install]
cmds = [
    "cd Portafolio-Astro && npm ci --legacy-peer-deps",
    "cd Terminal-KMP && chmod +x gradlew"
]

[phases.build]
cmds = [
    "cd Terminal-KMP && ./gradlew :webApp:wasmJsBrowserDistribution",
    "cd Portafolio-Astro && npm run build"
]

[start]
cmd = "cd Portafolio-Astro && node server.js"
